npm install babel-jest
npm install babel-preset-es2015
npm install babel-preset-react
npm install browserify
npm install coveralls
npm install gulp
npm install gulp-clean
npm install gulp-sass
npm install gulp-streamify
npm install gulp-uglify
npm install istanbul
npm install jasmine-node
npm install jest-cli
npm install react-addons-test-utils
npm install reactify
npm install streamify
npm install vinyl-source-stream
npm install watchify